version: "3.9"

services:
  auth:
    build:
      context: ./auth
    env_file:
      - ./auth/.env
    ports:
      - "8081:8081"

  verification:
    build:
      context: ./verification
    env_file:
      - ./verification/.env
    ports:
      - "8082:8082"
